# GAME GENERAL OPTIONS
TITLE = "Crazy Jumper"
GAME_FONT = "assets/fonts/cameria.ttf"
MENU_BACKGROUND = "assets/menu/menu.png"
WIDTH = 960
HEIGHT = 540
FPS = 60
CAMERA_SCROLL_GAP_X = 200
CAMERA_SCROLL_GAP_Y = 80
COLLISION_GAP = 4

# SOUND
MENU_SOUND = "assets/sounds/menu.wav"
OPTION_SOUND = "assets/sounds/option.wav"
SELECT_SOUND = "assets/sounds/select.wav"
JUMP_SOUND = "assets/sounds/jump.wav"
EXPLOSION_SOUND = "assets/sounds/explosion.wav"
PAUSE_SOUND = "assets/sounds/pause.wav"
FIRE_SOUND = "assets/sounds/fire.wav"
HIT_SOUND = "assets/sounds/hit.wav"
COIN_SOUND = "assets/sounds/coin.wav"

# COLORS
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# LOADING SCREEN
LOADING_SCREEN_WAITING_TIME = 300
LOADING_TITLE_SIZE = 60
LOADING_TITLE = "LOADING"
LOADING_COLOR = WHITE
LOADING_POS_X = 350
LOADING_POS_Y = 250

# GAME OVER SCREEN
GAME_OVER_SCREEN_WAITING_TIME = 1000
GAME_OVER_TITLE_SIZE = 60
GAME_OVER_TITLE = "GAME OVER"
GAME_OVER_COLOR = WHITE
GAME_OVER_POS_X = 300
GAME_OVER_POS_Y = 250

# GAME COMPLETED SCREEN
GAME_COMPLETED_SCREEN_WAITING_TIME = 3000
GAME_COMPLETED_TITLE_SIZE = 60
GAME_COMPLETED_TITLE = "THANKS FOR PLAYING"
GAME_COMPLETED_COLOR = WHITE
GAME_COMPLETED_POS_X = 140
GAME_COMPLETED_POS_Y = 250

# PLAYER PARAMETERS
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 80
INITIAL_PLAYER_LIVES = 3
PLAYER_INITIAL_LIFE = 120
PLAYER_COLLISION_WITH_ENEMY_REPOSITION_OFFSET = 35
PLAYER_HIT_BY_ENEMY_DAMAGE = 10

# PLAYER PHYSICS
F0 = 5000
UMAX = 320
UMIN = 30
FRICTION_COEFFICIENT = 1
MASS = 1
GRAVITY = 2400
JUMP_INITIAL_VELOCITY = -1100

# PLAYER ANIMATION
PLAYER_STANDING_FRAMES_NUMBER = 1
PLAYER_STAND_ANIMATION_FRAME_TIME = 80
PLAYER_WALK_FRAMES_NUMBER = 6
PLAYER_WALK_ANIMATION_FRAME_TIME = 40
PLAYER_JUMP_UP_FRAMES_NUMBER = 1
PLAYER_JUMP_DOWN_FRAMES_NUMBER = 1
PLAYER_JUMP_UP_ANIMATION_FRAME_TIME = 40
PLAYER_JUMP_DOWN_ANIMATION_FRAME_TIME = 40

# ENEMY ANIMATION
ENEMY_FRAMES_NUMBER = 2
ENEMY_WIDTH = 40
ENEMY_HEIGHT = 80
ENEMY_ANIMATION_FRAME_TIME = 80
ENEMY_INITIAL_LIFE = 100
ENEMY_DAMAGE_PER_FIREBALL = 25

# ENEMY FIRE
ENEMY_FIRE_SPAWN_TIME_INTERVAL = 800
ENEMY_FIRE_FRAMES_NUMBER = 3
ENEMY_FIRE_WIDTH = 50
ENEMY_FIREBALL_HEIGHT = 20
ENEMY_FIRE_ANIMATION_FRAME_TIME = 60
ENEMY_FIREBALL_RIGHT_OFFSET_X = 0
ENEMY_FIREBALL_LEFT_OFFSET_X = -50
ENEMY_FIREBALL_OFFSET_Y = -15
ENEMY_FIREBALL_VELOCITY_X = 0.8

# PLAYER FIREBALL ANIMATION
FIREBALL_FRAMES_NUMBER = 4
FIREBALL_WIDTH = 40
FIREBALL_HEIGHT = 10
FIREBALL_ANIMATION_FRAME_TIME = 40
FIREBALL_RIGHT_OFFSET_X = 10
FIREBALL_LEFT_OFFSET_X = -30
FIREBALL_OFFSET_Y = 30
FIREBALL_VELOCITY_X = 0.8
FIREBALL_Y_MOTION_INITIAL_VELOCITY = 0
FIREBALL_Y_GRAVITY_FACTOR = 0
FIREBALL_SPAWN_TIME_INTERVAL = 200

# COIN ANIMATION
COIN_WIDTH = 30
COIN_HEIGHT = 30
COIN_ANIMATION_FRAME_TIME = 50
COIN_FRAMES_NUMBER = 10

# SPLASH ANIMATION
SPLASH_WIDTH = 80
SPLASH_HEIGHT = 60
SPLASH_OFFSET_X = -20
SPLASH_OFFSET_Y = 30
SPLASH_FRAMES_NUMBER = 8
SPLASH_ANIMATION_FRAME_TIME = 60

# EXPLOSION ANIMATION
EXPLOSION_WIDTH = 64
EXPLOSION_HEIGHT = 64
EXPLOSION_OFFSET_X = -20
EXPLOSION_OFFSET_Y = -30
EXPLOSION_FRAMES_NUMBER = 16
EXPLOSION_ANIMATION_FRAME_TIME = 30

# MISCBAR PARAMETERS
MISCBAR_PLAYER_HEAD_WIDTH = 45
MISCBAR_PLAYER_HEAD_HEIGHT = 45
MISCBAR_COIN_FRAMES_NUMBER = 10
MISCBAR_COIN_ANIMATION_FRAME_TIME = 30
MISCBAR_COIN_WIDTH = 25
MISCBAR_COIN_HEIGHT = 25
MISCBAR_LIFEBAR_WIDTH = 200
MISCBAR_LIFEBAR_HEIGHT = 25
MISCBAR_LIFEBAR_BACKGROUND_COLOR = BLACK
MISCBAR_LIFEBAR_POS_X = 50
MISCBAR_LIFEBAR_POS_Y = 20
LIFEBAR_GAP = 1
MISCBAR_PLAYERS_HEAD_POS_X = 15
MISCBAR_PLAYERS_HEAD_POS_Y = 6
MISCBAR_COIN_POSITION_X = 275
MISCBAR_COIN_POSITION_Y = 20
MISCBAR_COIN_NUMBER_POS_X = 310
MISCBAR_COIN_NUMBER_POS_Y = 18
MISCBAR_COIN_NUMBER_FONT_SIZE = 35
MISCBAR_COIN_NUMBER_FONT_COLOR = BLACK
MISCBAR_LIVES_NUMBER_FONT_SIZE = 35
MISCBAR_LIVES_NUMBER_FONT_COLOR = BLACK
MISCBAR_LIVES_NUMBER_POS_X = 360
MISCBAR_LIVES_NUMBER_POS_Y = 18
MISCBAR_WORLD_NUMBER_FONT_SIZE = 35
MISCBAR_WORLD_NUMBER_FONT_COLOR = BLACK
MISCBAR_WORLD_NUMBER_POS_X = 330
MISCBAR_WORLD_NUMBER_POS_Y = 18

# MENU PARAMETERS
MENU_TITLE_TITLE = "CRAZY JUMPER"
MENU_TITLE_SIZE = 60
MENU_TITLE_COLOR = BLACK
MENU_TITLE_POS_X = 250
MENU_TITLE_POS_Y = 100
MENU_PLAY_TITLE = "PLAY"
MENU_PLAY_SIZE = 50
MENU_PLAY_COLOR = BLACK
MENU_PLAY_POS_X = 400
MENU_PLAY_POS_Y = 200
MENU_EXIT_TITLE = "EXIT"
MENU_EXIT_SIZE = 50
MENU_EXIT_COLOR = BLACK
MENU_EXIT_POS_X = 400
MENU_EXIT_POS_Y = 300
MENU_SELECT_COLOR = RED

# PAUSE PARAMETERS
PAUSE_TITLE_SIZE = 70
PAUSE_TITLE_TITLE = "GAME  PAUSED"
PAUSE_TITLE_COLOR = BLACK
PAUSE_TITLE_POS_X = 250
PAUSE_TITLE_POS_Y = 200

# **** WORLDS DESIGN ****
# WORLD DATA STORAGE
NUMBER_OF_WORLDS = 2
WORLD_MUSIC_DIRECTORY = []
WORLD_TILES_DIRECTORY = []
WORLD_BACKGROUND_DIRECTORY = []
WORLD_PLATFORM_LIST_DIRECTORY = []
WORLD_COIN_LIST_DIRECTORY = []
WORLD_ENEMY_LIST_DIRECTORY = []
WORLD_DOOR_DIRECTORY = []
WORLD_WIDTH_DIRECTORY = []
WORLD_HEIGHT_DIRECTORY = []
WORLD_INITIAL_X_DIRECTORY = []
WORLD_INITIAL_Y_DIRECTORY = []
WORLD_DEPTH_FACTOR_DIRECTORY = []
WORLD_BACKGROUND_WIDTH_DIRECTORY = []
WORLD_BACKGROUND_HEIGHT_DIRECTORY = []
WORLD_PLAYER_INITIAL_X_DIRECTORY = []
WORLD_PLAYER_INITIAL_Y_DIRECTORY = []

for world in range(NUMBER_OF_WORLDS):
    WORLD_MUSIC_DIRECTORY.append(0)
    WORLD_TILES_DIRECTORY.append(0)
    WORLD_BACKGROUND_DIRECTORY.append(0)
    WORLD_PLATFORM_LIST_DIRECTORY.append(0)
    WORLD_COIN_LIST_DIRECTORY.append(0)
    WORLD_ENEMY_LIST_DIRECTORY.append(0)
    WORLD_DOOR_DIRECTORY.append(0)
    WORLD_WIDTH_DIRECTORY.append(0)
    WORLD_HEIGHT_DIRECTORY.append(0)
    WORLD_INITIAL_X_DIRECTORY.append(0)
    WORLD_INITIAL_Y_DIRECTORY.append(0)
    WORLD_DEPTH_FACTOR_DIRECTORY.append(0)
    WORLD_BACKGROUND_WIDTH_DIRECTORY.append(0)
    WORLD_BACKGROUND_HEIGHT_DIRECTORY.append(0)
    WORLD_PLAYER_INITIAL_X_DIRECTORY.append(0)
    WORLD_PLAYER_INITIAL_Y_DIRECTORY.append(0)

# ----- WORLD 1 -----
# GENERAL PARAMETERS
WORLD = 1
WORLD_MUSIC_DIRECTORY[WORLD-1] = "assets/sounds/world_1.wav"
WORLD_WIDTH_DIRECTORY[WORLD - 1] = 4800
WORLD_HEIGHT_DIRECTORY[WORLD - 1] = 1080
WORLD_INITIAL_X_DIRECTORY[WORLD - 1] = 0
WORLD_INITIAL_Y_DIRECTORY[WORLD - 1] = HEIGHT - WORLD_HEIGHT_DIRECTORY[WORLD - 1]
WORLD_TILES_DIRECTORY[WORLD - 1] = "assets/level/level_1.png"
WORLD_BACKGROUND_DIRECTORY[WORLD - 1] = "assets/level/background_1.jpg"
WORLD_BACKGROUND_WIDTH_DIRECTORY[WORLD - 1] = 4800
WORLD_BACKGROUND_HEIGHT_DIRECTORY[WORLD - 1] = 1080
WORLD_DEPTH_FACTOR_DIRECTORY[WORLD - 1] = 0.3
WORLD_PLAYER_INITIAL_X_DIRECTORY[WORLD-1] = WIDTH * 0.25
WORLD_PLAYER_INITIAL_Y_DIRECTORY[WORLD-1] = HEIGHT * 0.5

# Door
WORLD_DOOR_DIRECTORY[WORLD-1] = (WORLD, 4690, 330, 45, 65)

# Platforms
WORLD_PLATFORMS_NUMBER = 15
WORLD_PLATFORM_LIST = []
for i in range(WORLD_PLATFORMS_NUMBER):
    WORLD_PLATFORM_LIST.append(0)

WORLD_PLATFORM_LIST[0] = (WORLD, 0, 1000, 500, 80)
WORLD_PLATFORM_LIST[1] = (WORLD, 650, 1000, 399, 80)
WORLD_PLATFORM_LIST[2] = (WORLD, 1050, 935, 100, 65)
WORLD_PLATFORM_LIST[3] = (WORLD, 1300, 935, 80, 65)
WORLD_PLATFORM_LIST[4] = (WORLD, 1500, 850, 80, 65)
WORLD_PLATFORM_LIST[5] = (WORLD, 1700, 800, 80, 65)
WORLD_PLATFORM_LIST[6] = (WORLD, 1920, 800, 500, 80)
WORLD_PLATFORM_LIST[7] = (WORLD, 2600, 720, 80, 65)
WORLD_PLATFORM_LIST[8] = (WORLD, 2800, 600, 80, 65)
WORLD_PLATFORM_LIST[9] = (WORLD, 2000, 450, 600, 50)
WORLD_PLATFORM_LIST[10] = (WORLD, 2200, 260, 100, 50)
WORLD_PLATFORM_LIST[11] = (WORLD, 2450, 200, 120, 40)
WORLD_PLATFORM_LIST[12] = (WORLD, 2750, 250, 750, 60)
WORLD_PLATFORM_LIST[13] = (WORLD, 3650, 400, 600, 100)
WORLD_PLATFORM_LIST[14] = (WORLD, 4400, 400, 400, 100)

WORLD_PLATFORM_LIST_DIRECTORY[WORLD-1] = WORLD_PLATFORM_LIST

# Enemies
ENEMIES_NUMBER = 6
ENEMY_LIST = []
for i in range(ENEMIES_NUMBER):
    ENEMY_LIST.append(0)

ENEMY_LIST[0] = (WORLD, 980, 920)
ENEMY_LIST[1] = (WORLD, 2340, 720)
ENEMY_LIST[2] = (WORLD, 2100, 370)
ENEMY_LIST[3] = (WORLD, 3000, 170)
ENEMY_LIST[4] = (WORLD, 3400, 170)
ENEMY_LIST[5] = (WORLD, 4560, 320)

WORLD_ENEMY_LIST_DIRECTORY[WORLD-1] = ENEMY_LIST

# Coins
COIN_NUMBER = 20
COIN_LIST = []
for i in range(COIN_NUMBER):
    COIN_LIST.append(0)

COIN_LIST[0] = (WORLD, 700, 800)
COIN_LIST[1] = (WORLD, 800, 800)
COIN_LIST[2] = (WORLD, 900, 800)
COIN_LIST[3] = (WORLD, 1950, 675)
COIN_LIST[4] = (WORLD, 2050, 675)
COIN_LIST[5] = (WORLD, 2150, 675)
COIN_LIST[6] = (WORLD, 2250, 675)
COIN_LIST[7] = (WORLD, 2230, 130)
COIN_LIST[8] = (WORLD, 2500, 80)
COIN_LIST[9] = (WORLD, 2900, 80)
COIN_LIST[10] = (WORLD, 3000, 80)
COIN_LIST[11] = (WORLD, 3100, 80)
COIN_LIST[12] = (WORLD, 3200, 80)
COIN_LIST[13] = (WORLD, 3300, 80)
COIN_LIST[14] = (WORLD, 3400, 80)
COIN_LIST[15] = (WORLD, 3700, 240)
COIN_LIST[16] = (WORLD, 3800, 240)
COIN_LIST[17] = (WORLD, 3900, 240)
COIN_LIST[18] = (WORLD, 4000, 240)
COIN_LIST[19] = (WORLD, 4100, 240)

WORLD_COIN_LIST_DIRECTORY[WORLD-1] = COIN_LIST


# ----- WORLD 1 -----
# GENERAL PARAMETERS
WORLD = 2
WORLD_MUSIC_DIRECTORY[WORLD-1] = "assets/sounds/world_2.wav"
WORLD_WIDTH_DIRECTORY[WORLD - 1] = 4800
WORLD_HEIGHT_DIRECTORY[WORLD - 1] = 1080
WORLD_INITIAL_X_DIRECTORY[WORLD - 1] = 0
WORLD_INITIAL_Y_DIRECTORY[WORLD - 1] = HEIGHT - WORLD_HEIGHT_DIRECTORY[WORLD - 1]
WORLD_TILES_DIRECTORY[WORLD - 1] = "assets/level/level_2.png"
WORLD_BACKGROUND_DIRECTORY[WORLD - 1] = "assets/level/background_2.jpg"
WORLD_BACKGROUND_WIDTH_DIRECTORY[WORLD - 1] = 4800
WORLD_BACKGROUND_HEIGHT_DIRECTORY[WORLD - 1] = 1080
WORLD_DEPTH_FACTOR_DIRECTORY[WORLD - 1] = 0.3
WORLD_PLAYER_INITIAL_X_DIRECTORY[WORLD-1] = WIDTH * 0.25
WORLD_PLAYER_INITIAL_Y_DIRECTORY[WORLD-1] = HEIGHT * 0.5

# Door
WORLD_DOOR_DIRECTORY[WORLD-1] = (WORLD, 4700, 510, 65, 70)

# Platforms
WORLD_PLATFORMS_NUMBER = 12
WORLD_PLATFORM_LIST = []
for i in range(WORLD_PLATFORMS_NUMBER):
    WORLD_PLATFORM_LIST.append(0)

WORLD_PLATFORM_LIST[0] = (WORLD, 0, 1000, 500, 80)
WORLD_PLATFORM_LIST[1] = (WORLD, 650, 1000, 500, 80)
WORLD_PLATFORM_LIST[2] = (WORLD, 1070, 820, 80, 65)
WORLD_PLATFORM_LIST[3] = (WORLD, 1210, 655, 80, 65)
WORLD_PLATFORM_LIST[4] = (WORLD, 1340, 520, 80, 65)
WORLD_PLATFORM_LIST[5] = (WORLD, 1560, 460, 600, 50)
WORLD_PLATFORM_LIST[6] = (WORLD, 1800, 250, 100, 50)
WORLD_PLATFORM_LIST[7] = (WORLD, 2045, 255, 120, 50)
WORLD_PLATFORM_LIST[8] = (WORLD, 2335, 300, 760, 60)
WORLD_PLATFORM_LIST[9] = (WORLD, 2975, 560, 500, 78)
WORLD_PLATFORM_LIST[10] = (WORLD, 3580, 390, 600, 100)
WORLD_PLATFORM_LIST[11] = (WORLD, 4400, 580, 400, 100)

WORLD_PLATFORM_LIST_DIRECTORY[WORLD-1] = WORLD_PLATFORM_LIST

# Enemies
ENEMIES_NUMBER = 7
ENEMY_LIST = []
for i in range(ENEMIES_NUMBER):
    ENEMY_LIST.append(0)

ENEMY_LIST[0] = (WORLD, 980, 920)
ENEMY_LIST[1] = (WORLD, 2000, 375)
ENEMY_LIST[2] = (WORLD, 2900, 220)
ENEMY_LIST[3] = (WORLD, 3000, 480)
ENEMY_LIST[4] = (WORLD, 3375, 480)
ENEMY_LIST[5] = (WORLD, 3600, 310)
ENEMY_LIST[6] = (WORLD, 4100, 310)


WORLD_ENEMY_LIST_DIRECTORY[WORLD-1] = ENEMY_LIST

# Coins
COIN_NUMBER = 15
COIN_LIST = []
for i in range(COIN_NUMBER):
    COIN_LIST.append(0)

COIN_LIST[0] = (WORLD, 700, 800)
COIN_LIST[1] = (WORLD, 800, 800)
COIN_LIST[2] = (WORLD, 900, 800)
COIN_LIST[3] = (WORLD, 1100, 700)
COIN_LIST[4] = (WORLD, 1235, 530)
COIN_LIST[5] = (WORLD, 1375, 380)
COIN_LIST[6] = (WORLD, 1840, 135)
COIN_LIST[7] = (WORLD, 2100, 135)
COIN_LIST[8] = (WORLD, 2400, 150)
COIN_LIST[9] = (WORLD, 2500, 150)
COIN_LIST[10] = (WORLD, 2600, 150)
COIN_LIST[11] = (WORLD, 2700, 150)
COIN_LIST[12] = (WORLD, 2800, 150)
COIN_LIST[13] = (WORLD, 2900, 150)
COIN_LIST[14] = (WORLD, 4500, 460)

WORLD_COIN_LIST_DIRECTORY[WORLD-1] = COIN_LIST
